services:
  db_transactions:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactions_db
    volumes:
      - transactions_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_TRANSACTION_PORT}:5432
    networks:
      - txnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  transaction_processor:
    build: ./transaction_processor
    volumes:
      - ./transaction_processor:/app
    depends_on:
      db_transactions:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db_transactions:5432/transactions_db
      FAULTY: 0.2
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    networks:
      - txnet

  kafka:
    image: apache/kafka:3.9.0
    init: true
    environment:
      KAFKA_LOG4J_LOGGERS: "kafka=WARN,kafka.controller=WARN,kafka.log.LogCleaner=WARN,state.change.logger=WARN,kafka.producer.async.DefaultEventHandler=WARN,kafka.coordinator.group.GroupMetadataManager=WARN"
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_LOG4J_TOOLS_LOGLEVEL: ERROR

      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_SESSION_TIMEOUT_MS: 5000
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 1000

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - txnet

  kafka-ui:
    image: provectuslabs/kafka-ui
    hostname: kafka-ui
    ports:
      - "8802:8080"
    depends_on:
      - kafka
    environment:
      LOGGING_LEVEL_ROOT: error
      LOGGING_LEVEL_COM_PROVECTUS: error
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - txnet

#  outbox_processor:
#    build: ./outbox_processor
#    volumes:
#      - ./outbox_processor:/app
#    depends_on:
#      transaction_processor:
#        condition: service_started
#      db_transactions:
#        condition: service_healthy
#      kafka:
#        condition: service_started
#    environment:
#      DATABASE_URL: postgres://postgres:postgres@db_transactions:5432/transactions_db
#      KAFKA_BROKER: kafka:9092
#      KAFKA_TOPIC: transactions
#      FAULTY: 0.2
#    init: true
#    tty: true
#    command: ["python", "outbox_processor.py"]
#    networks:
#      - txnet

  db_balance:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balance_db
    volumes:
      - balance_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_BALANCE_PORT}:5432
    networks:
      - txnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

#  inbox_processor:
#    build: ./inbox_processor
#    volumes:
#      - ./inbox_processor:/app
#    depends_on:
#      db_balance:
#        condition: service_healthy
#      kafka:
#        condition: service_started
#    environment:
#      DATABASE_URL: postgres://postgres:postgres@db_balance:5432/balance_db
#      KAFKA_BROKER: kafka:9092
#      KAFKA_TOPIC: transactions
#      FAULTY: 0.2
#    init: true
#    tty: true
#    command: ["python", "inbox_processor.py"]
#    networks:
#      - txnet

  balance_viewer:
    build: ./balance_viewer
    volumes:
      - ./balance_viewer:/app
    depends_on:
      db_balance:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db_balance:5432/balance_db
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8100"]
    init: true
    ports:
      - "8100:8100"
    networks:
      - txnet

  kafka_connect:
    image: confluentinc/cp-kafka-connect:latest
    depends_on:
      kafka:
        condition: service_started
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka_connect

      CONNECT_GROUP_ID: tx-connect-cluster
      CONNECT_CONFIG_STORAGE_TOPIC: tx-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: tx-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: tx-connect-status

      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"

      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    command:
      - bash
      - -c
      - |
        set -e
        echo "Installing Connector"
        confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest
        #
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run &
        #
        sleep infinity
    volumes:
      - ./connect:/docker-entrypoint-init.d
    ports:
      - "8083:8083"
    networks:
      - txnet

networks:
  txnet:
    driver: bridge
volumes:
  transactions_data: {}
  balance_data: {}
  kafka_data: {}
